version: '3.2'

services:
  web-pusher:
    container_name: web-pusher
    build:
      context: ${HUNCHO_DIR}/services/web-pusher
      dockerfile: ${HUNCHO_DIR}/services/web-pusher/build/Dockerfile
      args:
        NODE_VERSION: 12
    volumes:
      - ${HUNCHO_DIR}/services/web-pusher/src:/home/app/src
    env_file:
      - ${HUNCHO_DIR}/env/dev/.env.web-pusher
